joint_3_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: joint_3
    joint_speed: 1.17
    motor:
        id: 4
        init: 512
        min: 0
        max: 1023
joint_4_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: joint_4
    joint_speed: 1.17
    motor:
        id: 5
        init: 512
        min: 0
        max: 1023
joint_5_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: joint_5
    joint_speed: 1.17
    motor:
        id: 6
        init: 512
        min: 0
        max: 1023
