tetrapod_control_hw:
  loop_frequency: 10
  cycle_time_error_threshold: 0.2
  serial_interface: /dev/ttyUSB0
  baudrate: 1000000 # in bauds
  dynamixel_timeout: 0.05 # in seconds
  dynamixel_scanning: 0.05 # in seconds
  # correspondance between hardware IDs of the actuators and their names in ROS
  hardware_mapping:
    fl_leg_joint_0: 1
    fl_leg_joint_1: 2
    fl_leg_joint_2: 3
    fr_leg_joint_0: 4
    fr_leg_joint_1: 5
    fr_leg_joint_2: 6
    rl_leg_joint_0: 7
    rl_leg_joint_1: 8
    rl_leg_joint_2: 9
    rr_leg_joint_0: 10
    rr_leg_joint_1: 11
    rr_leg_joint_2: 12
  # offset to be added, in ticks, to the position of an actuator
  hardware_corrections:
    "1": 0
    "2": 0
    "3": 0
    "4": 0
    "5": 0
    "6": 0
    "7": 0
    "8": 0
    "9": 0
    "10": 0
    "11": 0
    "12": 0
